### ISSUE TITLE
Add event ID to event list

### ISSUE THREAD

**Issue by n8maninger** [SiaFoundation/walletd#130]
The event ID is not currently shown in the event list. Add a column and a dropdown for copying it.

![Screenshot 2024-06-11 at 9 57 58 AM](https://github.com/SiaFoundation/walletd/assets/5544150/268e7804-f079-4ea1-882c-43a91803403c)

**Comment by n8maninger** [comment]
This issue is incorrect
![Screenshot 2024-06-12 at 10 56 05 AM](https://github.com/SiaFoundation/walletd/assets/5544150/bbd7c759-a7e1-4c29-962f-36bed12cee12)

**Comment by alexfreska** [comment]
test

**Comment by n8maninger** [comment]
Test
