### ISSUE TITLE
app crash since update

### ISSUE THREAD

**Issue by bigmac5753** [SiaFoundation/walletd#163]
Mac app won't start since recent update, log also not showing any errors

**Comment by ChrisSchinnerl** [comment]
Are you running the desktop app or a binary you downloaded? Also what version are you running exactly?

**Comment by bigmac5753** [comment]
> Are you running the desktop app or a binary you downloaded? Also what version are you running exactly?

desktop 0.8.0

**Comment by alexfreska** [comment]
@bigmac5753 I'll take a look.

**Comment by alexfreska** [comment]
@bigmac5753 please try v0.9.0 via automatic update or: https://github.com/SiaFoundation/desktop/releases/tag/walletd%400.9.0

**Comment by bigmac5753** [comment]
updated to 0.9.0 but daemon still won't start

**Comment by alexfreska** [comment]
@bigmac5753 thank you for your patience, Ithe issue is that the `config.yaml` format changed and the daemon will not start with the old fields still present. Could you open your `config.yaml` and remove the 3 fields highlighted in the image below, `consensus.gatewayAddress`, `consensus.bootstrap`, and `consensus.enableUPnP`. These fields moved to `syncer`, re-saving the config will write them to the correct location, there just cannot be the extra fields that are no longer in use.

<img width="566" alt="Screenshot 2024-08-14 at 3 09 25 PM" src="https://github.com/user-attachments/assets/c0fe4d40-75a7-4ca9-88bc-3c74c57fe675">
<img width="492" alt="Screenshot 2024-08-14 at 3 09 35 PM" src="https://github.com/user-attachments/assets/08b41605-08af-422d-8d3a-10f7baa9949e">
<img width="222" alt="Screenshot 2024-08-14 at 3 10 00 PM" src="https://github.com/user-attachments/assets/39f55a3a-2fba-47b7-acce-0979e183d45b">

**Comment by bigmac5753** [comment]
thanks, this fixed the issue.
