### ISSUE TITLE
Docker Compose Issue - Inappropriate ioctl for device

### ISSUE THREAD

**Issue by JackPala** [SiaFoundation/walletd#183]
### Current Behavior

On new install after running docker compose up

`Enter password: Could not read input: inappropriate ioctl for device`

and container dies

### Expected Behavior

Enter password and hit enter

### Steps to Reproduce

docker compose up 

### Version

:latest

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

NixOS Linux

**Comment by n8maninger** [comment]
You need to set the password in the yaml file or in an environment variable.
