### ISSUE TITLE
Better handle yaml config compatibility

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/walletd#202]
### Current Behavior

```walletd
Electron's autoUpdater does not support the 'linux' platform. Ref: https://www.electronjs.org/docs/latest/api/auto-updater#platform-notices
stdout: loading config from /x/.config/walletd/data/config.yaml
failed to decode config file: yaml: unmarshal errors:
  line 16: field gatewayAddress not found in type config.Consensus
  line 17: field bootstrap not found in type config.Consensus
  line 18: field enableUPnP not found in type config.Consensus

child process exited with code 1
[55153:1213/043546.914126:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
```

The desktop process (or `walletd` itself) should be properly managing and migrating config so that old config structures dont cause a slient crash with zero logs. This can only be found by running `walletd` desktop in a shell.

### Expected Behavior

That I can start the server successfully

### Version

v0.12.2

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

 Mint Linux

**Comment by ChrisSchinnerl** [comment]
While we are not trying to break things on purpose, we are going to start providing compatibility guarantees once we reach a stable version (>=v1.0.0).
