### ISSUE TITLE
Zen only?

### ISSUE THREAD

**Issue by ukd1** [SiaFoundation/walletd#22]
I'm looking at Sia after years away, and looking at the new tooling. I'm wondering why is this zen only, yet also the downloadable wallet (at least from [this](https://sia.tech/software/walletd) page):

https://github.com/SiaFoundation/walletd/blob/ac5ced0b98f792b021529ddcec8f74063e720eac/cmd/walletd/main.go#L82

--> 

https://github.com/SiaFoundation/walletd/blob/ac5ced0b98f792b021529ddcec8f74063e720eac/cmd/walletd/node.go#L119

Which wallet is one supposed to use for mainnet?

**Comment by alexfreska** [comment]
hey there @ukd1, thank you for checking out our new software! We are rolling out some updates to the website this week to feature the new software and this was an oversight on my part. For renting and hosting we do want users to start with the new `renterd` and `hostd` software but the `walletd` wallet is indeed alpha. I will add the legacy Sia-UI and `siad` software to the Wallet page as official wallet options and make it clear that `walletd` is in alpha.

Once `walletd` is out of alpha it will default to mainnet with an optional `zen` flag. We are also exploring ways to package it up and make it more user-friendly for non-technical users.

**Comment by ukd1** [comment]
@alexfreska thanks - I must have popped back in at the least opportune time! BTW, loving the new look, thanks for the effort on them all.

OT, but is there anything public that needs work on this new set of software? I saw the S3 gateway proposal suggestion, which seems fun, but is there anything smaller?

**Comment by alexfreska** [comment]
@ukd1 Indeed 😅 I will get the software on the Wallet page updated today, and thank you for the kind words!

The S3 gateway is definitely a pretty big one haha, some of the project ideas listed on the website are a bit smaller, but we clearly need to add a variety of smaller ones 👍🏼.

Anything you are specifically interested in? The script @lukechampine mentioned in https://github.com/SiaFoundation/walletd/issues/23 would be very useful as `walletd` heads towards beta, as users like yourself will need to migrate - this could potentially be integrated into `walletd` as an wallet migration/import feature. Besides this @lukechampine @n8maninger any ideas?

**Comment by ukd1** [comment]
@alexfreska I've built a (simple) S3 server before, and I'm sure there is a go-version that could be used as a base, but yea, it's probably pretty big for a first thing. The script / idea mentioned in #23 seems like something smaller, and fixes a problem I actually have personally...open to other ideas though - I'm still long-SIA as one of the imho few coins with actual utility 🤘
