### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/walletd#70]
I consider this a low priority, but given that PostgreSQL is being added, I would also like to request MySQL.

The main reason is that I can see supporting SC as payment in the far future. I would prefer to not need to run another database infra (which would increase the infra cost) since everything else would run under MySQL.

Thanks.

**Comment by n8maninger** [comment]
We do not currently plan to support MySQL in `hostd`, `walletd` or `explored`.
