### ISSUE TITLE
28/29 word "Sia" recovery phrase support

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/walletd#79]
We should be able to create a WASM function for this pretty easily.
Every wallet since `walrus` has been backwards-compatible with `siad` seeds. `siad` seeds are 32 bytes of entropy, which are hashed with an integer to derive sequential keys; `walrus` seeds are 16 bytes of entropy, which are hashed to produce 32 bytes, which are then hashed with an integer. So the only difference is that `walrus` seeds get hashed an extra time before you use them.

**Comment by n8maninger** [comment]
We will not support Sia 28/29 seeds in the `walletd` UI. Instead, we will follow `hostd` and create a utility to sweep the funds of legacy wallet formats, both Sia seed and v0.3.x siag key files.
