### ISSUE TITLE
walletd Compilation Issue: No Task Nodes Found on Execution

### ISSUE THREAD

**Issue by ps2xu** [SiaFoundation/walletd#82]
Hello,

I’ve encountered an issue after compiling walletd. Here are the steps I followed:

>Set **CGO_ENABLED=1**.
>Updated the %PATH% environment variable to include the GCC directory.
>Ran the command ```go generate ./...```
>Followed by ```go build -o ./bin/ ./cmd/walletd```

After these steps, I obtained an executable .exe file. However, when I run this executable, I receive an error stating ```couldn't discover UPnP router   {"error": "no UPnP-enabled gateway found"}```

Could you please help me understand the potential causes of this error? Any guidance or suggestions would be greatly appreciated.

Thank you!
```
E:\SiaData\sia>walletd
walletd v0.1.0
Enter API password:
[35mDEBUG[0m  couldn't discover UPnP router   {"error": "no UPnP-enabled gateway found"}
[34mINFO[0m   stdlib  p2p: Listening on [::]:9981
[34mINFO[0m   stdlib  api: Listening on 127.0.0.1:9980
[31mERROR[0m  syncer.peerLoop failed to fetch peers   {"error": "transaction failed (attempt 1): failed to scan peer info: sql: expected 1 destination arguments in Scan, not 5"}
[31mERROR[0m  syncer.peerLoop failed to fetch peers   {"error": "transaction failed (attempt 1): failed to scan peer info: sql: expected 1 destination arguments in Scan, not 5"}
[31mERROR[0m  syncer.peerLoop failed to fetch peers   {"error": "transaction failed (attempt 1): failed to scan peer info: sql: expected 1 destination arguments in Scan, not 5"}
[31mERROR[0m  syncer.peerLoop failed to fetch peers   {"error": "transaction failed (attempt 1): failed to scan peer info: sql: expected 1 destination arguments in Scan, not 5"}
[31mERROR[0m  syncer.peerLoop failed to fetch peers   {"error": "transaction failed (attempt 1): failed to scan peer info: sql: expected 1 destination arguments in Scan, not 5"}
[31mERROR[0m  syncer.peerLoop failed to fetch peers   {"error": "transaction failed (attempt 1): failed to scan peer info: sql: expected 1 destination arguments in Scan, not 5"}
```

**Comment by ChrisSchinnerl** [comment]
Thanks for reporting. `no UPnP-enabled gateway found` is not an issue, it just means `walletd` can't automatically forward a port. The `transaction failed` error is definitely an issue though and will be fixed asap.
In the meantime I'd recommend sticking to the tagged releases of `walletd`.
