### ISSUE TITLE
The transaction flow should use the txpool recommended fee endpoint

### ISSUE THREAD

**Issue by alexfreska** [SiaFoundation/walletd#89]

**Comment by alexfreska** [comment]
@n8maninger does `walletd`s fee endpoint returns recommended fee per byte? Meaning the fee should be calculated as `fee` * bytes in encoded transaction? If so, what is the best way to calculate the fee if the exact transaction size is not known until after calling /fund, which requires passing the fee.

**Comment by n8maninger** [comment]
It is the recommended fee per byte.

The correct way would be to call `fund`, release the inputs, estimate the fee, then call `fund` again with the estimate.

The way you should do it is to get the recommended fee and hardcode a size of 1000 bytes.

**Comment by alexfreska** [comment]
> The correct way would be to call fund, release the inputs, estimate the size and multiply by fee, then call fund again with the fee estimate.

Isn't there a slight chance it would select different inputs?

> The way you should do it is to get the recommended fee per byte and multiply it by 1000 bytes.

Do you mean to do this rather than the tedious "correct" way, just charge for 1000 bytes and thats roughly always good?

**Comment by n8maninger** [comment]
> Do you mean to do this rather than the tedious "correct" way, just charge for 1000 bytes and thats roughly always good?

Exactly. Most transactions are less than 1000 bytes and the cost difference is negligible.
